# -*- coding: utf-8 -*-
"""Progetto unico_Piattaforme per i Big Data & Machine learning_Mastropietro R_880HHHINGINFOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zyqH0ofabQOK48K5psVIXJiLj5oGMENB

# 1. Far funzionare una piattaforma per i big data
"""

# @title Installazione della API PySpark in Google Colab (fonte: https://colab.research.google.com/drive/1fa2G3YuXx3Isqyby5kFETqmWotFwtqlH?usp=sharing#scrollTo=hxv7w_2y2bb9)
!sudo apt update
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q https://dlcdn.apache.org/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz
!tar xf spark-3.2.1-bin-hadoop3.2.tgz
!pip install -q findspark
!pip install pyspark
!pip install py4j

import os
import sys
# os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
# os.environ["SPARK_HOME"] = "/content/spark-3.2.1-bin-hadoop3.2"

import findspark
findspark.init()
findspark.find()

import pyspark

from pyspark.sql import DataFrame, SparkSession
from typing import List
import pyspark.sql.types as T
import pyspark.sql.functions as F

spark= SparkSession \
       .builder \
       .appName("Breast Cancer Analysis") \
       .getOrCreate()

spark

"""# 2. Importare un dataset (citando la fonte)"""

# @title Creazione di un dataframe (sdf) dal dataset "Breast_cancer_dataset.csv" (fonte: https://www.kaggle.com/datasets/wasiqaliyasir/breast-cancer-dataset)
sdf = spark.read.csv("/content/Breast_cancer_dataset.csv", header=True, inferSchema=True)

"""Il set di dati proviene dal Breast Cancer Wisconsin (Diagnostic) Data Set, un benchmark ampiamente utilizzato nell'apprendimento automatico per la diagnostica medica. Contiene misurazioni dettagliate dei nuclei cellulari da campioni di tessuto mammario, consentendo la classificazione dei tumori come benigni (non cancerosi) o maligni (cancerosi).

## Obiettivi dell'analisi

Ho scelto il presente dataset perché interessato alle applicazioni della scienza dei dati in ambito biomedico, e poter trarre utili informazioni da dati reali sulla diagnostica patologica mi è sembrato un ottimo punto di partenza per eventuali successivi lavori di approfondimento.

Anche se il dataset in questione non presenta dimensioni particolarmente impegnative in termini di consumo delle risorse di calcolo, per assolvere agli obiettivi didattici dei corsi di "Piattaforme per i big data" e "Machine learning" del corso di laurea magistrale in ingegneria informatica della Università Telematica Internazionale UniNettuno, partirò non l'utilizzo di una nota piattaforma per la gestione dei big data "Spark" - nella sua implementazione Pyton con la API "PySpark" - creando un dataframe dal file "Breast_cancer_dataset.csv" (di cui ne citerò la fonte).

I primi passi dell'analisi consisteranno nell'estrapolare un sottoinsieme ridotto di dati e, utilizzando la nota distribuzione API Pandas, nell'ottenere le classiche informazioni descrittive di carattere strutturale del dataset (nomi delle colonne, tipi dei dati, presenza di campi vuoti o duplicati, etc.).

Successivamente, tornerò a gestire il dataset originario effettuando operazioni di pulizia e aggregazione dei dati finalizzate all'ottenimento di un nuovo dataframe costituito da un sottoinsieme di interesse per gli obiettivi dell'analisi.

Riprendendo l'utilizzo della ricca libreria delle classi di Pandas, effettuerò inizialmente analisi di tipo esplorativo; successivamente - servendomi di note tecniche di data visualization - ricercherò possibili correlazioni fra le più significative delle variabili disponibili e la classificazione dei tumori.

In ultima analisi, implementerò alcuni fra i più noti algoritmi di machine learning che, con un addestramento basato su una selezione di dati che limiti il fenomeno dell'overfitting, riclassifichi i tumori con un livello di attendibilità utile a possibili applicazioni future.

# 3. Data exploration su un sottoinsieme del dataset usando le librerie Pandas
"""

# @title Stampa delle dimensioni del dataframe
print(f"{sdf.count()} Rows x {len(sdf.columns)} Columns")

# @title Creazione di un nuovo dataframe (sdf2) con le prime 50 righe del dataset
sdf2 = sdf.limit(50)

# @title Conversione (con Arrow) da PySpark dataframe (sdf2) a Pandas dataframe (pdf2)
pdf2 = sdf2.toPandas()

# @title Installazione delle API Pandas (fonte: https://pandas.pydata.org/) e NumPy (fonte: https://pypi.org/project/numpy/)
!pip install pandas
!pip install numpy

import pandas as pd
import numpy as np

# @title Stampa delle prime 5 righe (head)
pdf2.head()

# @title Stampa delle info sul dataframe (colonne, conteggi valori nulli, tipi)
pdf2.info()

# @title Ricerca di eventuali valori che si ripetono nei record
pdf2.duplicated().any()

# @title Installazione della API Matplotlib (fonte: https://pypi.org/project/matplotlib/)
!pip install matplotlib

import matplotlib.pyplot as plt

# @title Installazione della API Seaborn (fonte: https://seaborn.pydata.org/)
!pip install seaborn

import seaborn as sns

# @title Creazione di un nuovo dataframe (pdf3) senza le colonne "id", "diagnosis" e "_c32"
pdf3 = pdf2.drop(["id", "diagnosis", "_c32"], axis=1)

# @title Calcolo dei principali indici statistici
pdf3.describe()

# @title Heatmap dei coefficienti di correlazione di rango di Spearman
plt.figure(figsize=(18,16))
sns.heatmap(pdf3.corr(method='spearman'), cmap='bwr', annot=True)
plt.title('Heatmap dei coefficiente di correlazione di rango di Spearman')
plt.show()

"""# 4. Data exploration per conferma e data cleaning su tutto il dataset

Secondo il coefficiente di rango di Spearman, i valori vicini all'unità sarebbero altamente correlabili; anche i valori prossimi allo zero potrebbero risultare potenzialmente correlabili secondo tale coefficiente.

Dalla heatmap di cui sopra si osserva una certa ripetitività nella correlazione fra i parametri di misura afferenti alle tre categorie contemplate nel dataset: Valori medi, Errore standard, Valori peggiori.

Ho deciso, quindi, di concentrare il resto dell'analisi sui campi relativi ai valori medi delle misurazioni. Proseguirò, dunque, riconsiderando tutte le righe del dataset di partenza, ma estrapolando solo i dati appartenenti alle colonne: "diagnosis", "radius_mean", "texture_mean", "perimeter_mean", "area_mean", "smoothness_mean", "compactness_mean", "concavity_mean", "concave points_mean", "symmetry_mean", "fractal_dimension_mean".
"""

# @title Stampa delle prime 5 righe
sdf.show(n=5)

# @title Stampa delle info sul dataframe (colonne, tipi)
sdf.printSchema()

# @title Ricerca di eventuali record con stesso "id"
if sdf.count() == sdf.dropDuplicates(subset=['id']).count():
  print('False')
else:
  print('True')

# @title Calcolo dei principali indici statistici
sdf.summary().show()

"""Si osservi come il valore dei principali indici statistici non cambi significativamente dall'analisi effettuata su 50 unità a quella ripetuta per l'intero dataset di 569 record."""

# @title Estrarre un dataframe di interesse (sdf4)
sdf4 = sdf.select("diagnosis", "radius_mean", "texture_mean", "perimeter_mean", "area_mean", "smoothness_mean", "compactness_mean", "concavity_mean", "concave points_mean", "symmetry_mean", "fractal_dimension_mean")
sdf4.show(n=5)

# @title Conversione (con Arrow) da PySpark dataframe (sdf4) a Pandas fataframe (pdf4)
pdf4 = sdf4.toPandas()

"""# 5. Data analysis e data visualizazion con Pandas"""

# @title Conteggio dei casi di tumore benigno (B) e di tumore maligno (M)
pdf4['diagnosis'].value_counts()

# @title Scatter Matrix con distinzione dei dati per diagnosi
sns.pairplot(pdf4, hue="diagnosis", corner=True)

"""Dalla matrice presentata si evince la ovvia correlabiità fra le misure medie dei raggi e le rispettive misure medie di perimetro e area. Considerazioni analoghe possono esser fatte fra la concavità media e la media delle porzioni concave nel contorno.

La distinzione fatta fra i campioni cancerosi (M) e non-cancerosi (B), negli scatter plot generati, ha consentito di riconoscere visivamente i due pattern; inoltre, tale distinzione risulta particolarmente evidente per alcune coppie fra gli attributi considerati.

Utili indicazioni sono fornite anche dalla diagonale delle KDE (Kernel Density Estimation), dalla quale si evince una sostanziale sovrapposizione nella classificazione della diagnosi per i campi relativi a "texture_mean", "smoothness_mean", "symmetry_mean" e "fractal_dimension_mean".

In ragione delle osservazioni espresse ho deciso di considerare come variabili di interesse per le successive analisi il raggio, la compattezza e la concavità.
"""

# @title Creazione di un nuovo dataframe ridotto (pdf5)
pdf5 = pdf4.drop(["texture_mean", "perimeter_mean", "area_mean", "smoothness_mean", "concave points_mean", "symmetry_mean", "fractal_dimension_mean"], axis=1)

# @title Scatter Matrix ridotta con distinzione dei dati per diagnosi
sns.pairplot(pdf5, hue="diagnosis", corner=True)

# @title Installazione della API Plotly e importazione della libreria Plotly express (fonte: https://plotly.com/python/)
!pip install plotly

import plotly.express as px

"""Come ultimo approfondimento della presente analisi - prima di passare alla creazione di un opportuno modello di machine learning - ho ritenuto utile rimarcare come la distinzione fra i pattern della diagnosi dei casi registrati si mostri particolarmente chiara al variare delle tre variabili considerate; la seguente rappresentazione (interattiva) in scatter plot tridimensionale ne agevola l'osservazione."""

# @title 3D Scatter Plot delle variabili “radius_mean”, “compactness_mean” e “concavity_mean”
fig = px.scatter_3d(pdf5, x='radius_mean', y='compactness_mean', z='concavity_mean',
              color='diagnosis', opacity= 0.75, width=1150, height=950)
fig.show()

"""## Prime considerazioni sull'analisi condotta

La visualizzazione interattiva appena mostrata ha evidenziato - a meno di qualche valore anomalo (outlier) - una maggiore concentrazione dei casi di tumore cancerosi all'aumentare delle metriche considerate. Di contro, la restante compagine con diagnosi bengigna risulta addensata in un range ridotto degli stessi parametri.

# 6. Creare un modello di Machine Learning per una predizione o classificazione
"""

# @title Installazione della API scikit-learn (fonte: https://scikit-learn.org/stable/)
!pip install scikit-learn

import sklearn

# @title Importazione delle librerie utili
from sklearn.model_selection import train_test_split    # metodo per separate i dati di addestramento dai dati di test
from sklearn.preprocessing import RobustScaler          # metodo per ridurre dimensionalità e outliers nel dataset
from sklearn.metrics import accuracy_score              # metodo per calcolare l'accuratezza della stima
from sklearn.metrics import precision_score             # metodo per calcolare la precisione della stima
from sklearn.metrics import f1_score                    # metodo per calcolare il punteggio F1 della stima
from sklearn.metrics import RocCurveDisplay             # metodo per visualizzare la curva ROC

# Classificatori
from sklearn.neighbors import KNeighborsClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.ensemble import RandomForestClassifier     # non richiede la riduzione in scala delle caratteristiche
from sklearn.tree import DecisionTreeClassifier         # non richiede la riduzione in scala delle caratteristiche

"""### Generazione di un nuovo dataframe (pdf6) con mappatura della diagnosi (M:0, B:1)

La codifica (in numeri interi) dei dati categorici (in formato stringa) relativi alla diagnosi favorisce gli algoritmi di machine learning nell'interpretazione di tali dati durante le fasi di addestramento.
"""

pdf6 = pdf5.copy()
pdf6['diagnosis'] = pdf6['diagnosis'].map({'M': 0, 'B': 1})

pdf6.head()

"""### Preparazione dei dataframe di addestramento e test

Nella pratica comune si tende ad aumentare la frazione di dati destinata ai test per dataset modesti. In questo caso ho ritenuto il rapporto 0.2 (test_size) un giusto compromesso per le analisi.

Assegnando un seme casuale fisso (random_state) al generatore interno di numeri pseudo-casuali (il numero 42 ha un mero valore simbolico) si garantisce la riproducibilità dei risultati ottenuti.

Il parametro preposto alla stratificazione (stratify), inoltre, garantirà un'equa distribuzione fra le righe del set di addestramento in funzione delle categorie target (y).
"""

X = pdf6.drop('diagnosis', axis=1)
y = pdf6['diagnosis']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

"""### Riduzione in scala delle caratteristiche

Rendere confrontabile l'ordine di grandezza delle caratteristiche considerate risulta un passaggio fondamentale per il rendimento della maggior parte degli algoritmi di machine learning (dei classificatori prescelti, solo il RandomForest non risulta influenzato dalla scala dei valori). Tale operazione è perseguibile con il metodo StandardScaler() di scikit-learn; tuttavia, adotterò un altro valido metodo di riduzione, il RobustScaler(), che risulta più adatto all'applicazione su dataset minori contenenti valori anomali.
"""

RS = RobustScaler()

X_train_scaled = RS.fit_transform(X_train)
X_test_scaled = RS.transform(X_test)

# @title Applicazione di 4 modelli di classificazione scelti
KNC = KNeighborsClassifier()
KNC.fit(X_train_scaled, y_train)
y_predict = KNC.predict(X_test_scaled)

GPC = GaussianProcessClassifier()
GPC.fit(X_train_scaled, y_train)
y_predict2 = GPC.predict(X_test_scaled)

RFC = RandomForestClassifier()
RFC.fit(X_train, y_train)    # ho usato i dati originari perché questo classificatore non risente della scala
y_predict3 = RFC.predict(X_test)

DTC = DecisionTreeClassifier()
DTC.fit(X_train, y_train)    # ho usato i dati originari perché questo classificatore non risente della scala
y_predict4 = DTC.predict(X_test)

# @title Calcolo dell'accuratezza nella stima per ciascun modello
y_accuracy = accuracy_score(y_test, y_predict)
y_accuracy2 = accuracy_score(y_test, y_predict2)
y_accuracy3 = accuracy_score(y_test, y_predict3)
y_accuracy4 = accuracy_score(y_test, y_predict4)

print(f"Accuratezza KNeighborsClassifier: {round(y_accuracy, 2)}")
print(f"Accuratezza GaussianProcessClassifier: {round(y_accuracy2, 2)}")
print(f"Accuratezza RandomForestClassifier: {round(y_accuracy3, 2)}")
print(f"Accuratezza DecisionTreeClassifier: {round(y_accuracy4, 2)}")

# @title Calcolo della precisione nella stima per ciascun modello
y_precision = precision_score(y_test, y_predict)
y_precision2 = precision_score(y_test, y_predict2)
y_precision3 = precision_score(y_test, y_predict3)
y_precision4 = precision_score(y_test, y_predict4)

print(f"Precisione KNeighborsClassifier: {round(y_precision, 2)}")
print(f"Precisione GaussianProcessClassifier: {round(y_precision2, 2)}")
print(f"Precisione RandomForestClassifier: {round(y_precision3, 2)}")
print(f"Precisione DecisionTreeClassifier: {round(y_precision4, 2)}")

# @title Calcolo del punteggio F1 nella stima per ciascun modello
y_F1S = f1_score(y_test, y_predict)
y_F1S2 = f1_score(y_test, y_predict2)
y_F1S3 = f1_score(y_test, y_predict3)
y_F1S4 = f1_score(y_test, y_predict4)

print(f"Punteggio F1 KNeighborsClassifier: {round(y_F1S, 2)}")
print(f"Punteggio F1 GaussianProcessClassifier: {round(y_F1S2, 2)}")
print(f"Punteggio F1 RandomForestClassifier: {round(y_F1S3, 2)}")
print(f"Punteggio F1 DecisionTreeClassifier: {round(y_F1S4, 2)}")

# @title Generazione della curva di ROC e calcolo del punteggio di AUC per ciascun modello
fig = plt.figure(figsize=(8, 8), constrained_layout=True)
ax_array = fig.subplots(2, 2, squeeze=False)

RocCurveDisplay.from_estimator(KNC, X_test_scaled, y_test, ax=ax_array[0, 0])
RocCurveDisplay.from_estimator(GPC, X_test_scaled, y_test, ax=ax_array[0, 1])
RocCurveDisplay.from_estimator(RFC, X_test, y_test, ax=ax_array[1, 0])
RocCurveDisplay.from_estimator(DTC, X_test, y_test, ax=ax_array[1, 1])

plt.show()

"""## Considerazioni conclusive

Riporto di seguito una breve descrizione delle metriche considerate nell'ambito del presente progetto per valutare la bontà della stima dei classificatori utilizzati.

### Accuratezza

E' un indice generale che rappresenta la frazione di previsioni esatte (veri positivi e veri negativi) rispetto al numero di tutte le istanze (veri positivi, veri negativi, falsi positivi e falsi negativi).

### Precisione
Rappresenta la frazione di previsioni corrette (veri positivi) rispetto a tutte le istanze positive (veri e falsi). In ambito clinico è un indice molto considerato.

### Punteggio F1
E' definito dalla media armonica di precisione e richiamo; quest'ultimo è dato dal numero di veri positivi rapportato alla somma di veri positivi e falsi negativi. Il punteggo F1 risulta, pertanto, un indice bilanciato, utile a valutare le prestazioni di un algoritmo quando sia i falsi positivi che i falsi negativi sono importanti (come nei casi clinici).

### Curva ROC
E' la rappresentazione grafica dell'andamento della frazione (0-1) dei veri positivi al variare ella frazione (0-1) dei falsi positivi.
La prestazione ottimale di un classificatore mostrerebbe un gomito ben definito nell'angolo in alto a sinistra del grafico.

### AUC (area sotto la curva ROC)
Direttamente collegato alla curva ROC, è un indice di probabilità che il modello scelga un vero positivo rispetto ad un falso positivo in una classificazione binaria.

### **Pensiero critico**
I risultati delle metriche applicate ai classificatori scelti per il lavoro presentato hanno rivelato accuratezza, precisione e un punteggio F1 maggiori per il RandomForest, nonché una migliore qualità della curva ROC, seguita da un alto valore AUC (0,98), per lo stesso algoritmo.

L'esito delle operazioni condotte hanno confermato, pertanto, la bontà delle attività di analisi esplorativa e selezione dei dati, effettuate preliminarmente al fine di estrapolare un dataset idoneo per l'addestramento degli algoritmi di machine learning adottati.
"""